apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistent.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
  storageClassName: {{ .Values.persistent.storageClassName }}
